service: my-express-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY 
          cors: true
      - http: 
          path: '/{proxy+}'
          method: ANY
          cors: true
      

plugins:
  - serverless-offline